environments:
    - name: dev
      configs: 
          endpoints:
              production:
                  url: https://dev.sample.com
              sandbox:
                  url: https://dev.sample.com
          deploymentEnvironments:
              - displayOnDevportal: ture
                deploymentEnvironment: Default
                deploymentVhost: localhost
    - name: prod
      configs: 
          endpoints:
              production:
                  url: https://prod.sample.com
              sandbox:
                  url: https://prod.sample.com
          deploymentEnvironments:
              - displayOnDevportal: true
                deploymentEnvironment: Default
                deploymentVhost: localhost